#
# SfePy minimal appveyor.yml config file
#
# YAML Reference Config:         https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
# YAML Validator:                https://ci.appveyor.com/tools/validate-yaml
#

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
#version: ''

init:

  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "SfePy-$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "SfePy-$($env:APPVEYOR_REPO_COMMIT.substring(0,8))"
      }

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: false

environment:
  matrix:

    - PYTHON: "C:\\Python37_64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"

install:
  # If there is a newer build queued for the same PR, cancel this one.

  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  #
  # Install (and update) the appropriate Miniconda.
  #
  - powershell .\\deployment-CI\\miniconda-install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge

  - cmd.exe /c conda init

  - "conda create -q -n sfepy-test python=%PYTHON_VERSION% numpy scipy cython matplotlib pytables pyparsing sympy"
  - conda activate sfepy-test
  #
  # Scikit UMFPACK (TBD)
  #
  # IGA kit
  # Install mingw/gfortran build tools
  #
  - conda install -q m2w64-gcc m2w64-gcc-libs m2w64-gcc-libs-core m2w64-gcc-fortran
  #- conda install -q libpython
  #
  #- pip install https://bitbucket.org/dalcinl/igakit/get/default.tar.gz
  - pip install --global-option build_ext --global-option --compiler=mingw32 https://bitbucket.org/dalcinl/igakit/get/0a87ac7cbffb.zip
  #
  # Revert back to native MSVC build tools
  #
  # - conda remove -q libpython
  #

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to disable automatic builds
build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:

  - python setup.py build_ext --inplace
  - ps: |
      python run_tests.py
      if ($LastExitCode -ne 0) { python run_tests.py --raise }

#---------------------------------#
#         notifications           #
#---------------------------------#

# Please note: notifications settings are merged with GUI settings!
notifications:

  # Email
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
