#
# SfePy minimal ammveyor.yml config file
#
# YAML Reference Config:         https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
# YAML Validator:                https://ci.appveyor.com/tools/validate-yaml
#

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: ''

init:

  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "SfePy-$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "SfePy-$($env:APPVEYOR_REPO_COMMIT.substring(0,8))"
      }

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: false

environment:
  matrix:

    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python36_32"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      CONDA_PY: "36"

    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

install:
  # If there is a newer build queued for the same PR, cancel this one.

  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  #
  # Install (and update) the appropriate Miniconda.
  #
  - powershell .\\deployment-CI\\miniconda-install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "conda create -q --yes -n sfepy-test python=%PYTHON_VERSION% numpy scipy cython matplotlib pytables pyparsing sympy"
  - activate sfepy-test
  #
  # TBD: (still looking for working version...)
  #- pip install scikit-sparse "scikit-umfpack==0.2.3"
  #
  - conda info -a
  - python -V

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to disable automatic builds
build: false

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:

  - "python setup.py build_ext --inplace"
  - "python run_tests.py"

#
# Probably not needed here...
#
#  - ps: |
#      python run_tests.py
#      if ($LastExitCode -ne 0) { python run_tests.py --raise }

#---------------------------------#
#         notifications           #
#---------------------------------#

# Please note: notifications settings are merged with GUI settings!
notifications:

  # Email
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
