#
# SfePy minimal travis.yml config file
#
# YAML Validator:   http://lint.travis-ci.org/
#

language: python

#
# Enable Container-based testing
#
sudo: false
dist: xenial

matrix:
  include:
    - python: 2.7
    - python: 3.7

addons:
  apt:
    packages:
    - libsuitesparse-dev
    - swig
    - gfortran

cache:
  directories:
    - $HOME/.cache/pip

before_install:

  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:

  - conda init bash
  - source $(conda info --root)/etc/profile.d/conda.sh # TBD: should be made better...
  - conda create -q -n sfepy-test python=$TRAVIS_PYTHON_VERSION numpy scipy cython matplotlib pytables pyparsing sympy
  - conda activate sfepy-test

  - conda info -a
  - python -V

  - pip install scikit-umfpack
  - pip install https://bitbucket.org/dalcinl/igakit/get/default.tar.gz

script:

  - python setup.py build_ext --inplace
  - python run_tests.py; export SFEPY_TEST_RESULTS=$?; (exit $SFEPY_TEST_RESULTS)
  - |
    if [ $SFEPY_TEST_RESULTS -ne 0 ]; then
      python run_tests.py --raise
    fi

notifications:
  email: false